  services:
    tailscale: 
      container_name: tailscale 
      hostname: tailscale-homebots
      image: tailscale/tailscale:stable 
      volumes: 
        - ./tailscale:/var/lib # State data will be stored in this directory 
        - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
      cap_add: # Required for tailscale to work 
        - net_admin 
        - sys_module 
      command: tailscaled 
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_EXTRA_ARGS=--advertise-exit-node
      privileged: true 
      restart: unless-stopped
