{
 "title": "UniFi-Poller: USG Insights - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays detailed information for security gateways in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller",
  "usg"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_device_info{type=~\"udm|usg|ugw\"},source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_device_info{source=~\"$Controller\", type=~\"udm|usg|ugw\"},site_name)"
   },
   {
    "name": "Gateway",
    "query": "label_values(unpoller_device_info{site_name=~\"$Site\", type=~\"udm|usg|ugw\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Gateway Details",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_info{site_name=~\"$Site\", name=~\"$Gateway\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"})"
    }
   ]
  },
  {
   "title": "Site: $Site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Site",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Uptime"
      }
     ]
    },
    {
     "title": "Speed Test",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_speedtest_upload{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Upload"
      },
      {
       "expr": "unpoller_device_speedtest_download{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} Download"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 9, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (unpoller_device_speedtest_runtime_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})",
       "legendFormat": "{{name}} Test Time"
      },
      {
       "expr": "sum by (name) (unpoller_device_uplink_latency_seconds{site_name=~\"$Site\", name=~\"$Gateway\"})",
       "legendFormat": "{{name}} Uplink Latency"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_cpu_utilization_ratio{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} CPU %"
      },
      {
       "expr": "unpoller_device_memory_utilization_ratio{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} RAM %"
      }
     ]
    },
    {
     "title": "Uplink",
     "type": "stat",
     "description": "WAN Port Speed",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_uplink_speed_mbps{site_name=~\"$Site\", name=~\"$Gateway\"}"
      }
     ]
    },
    {
     "title": "Desktop",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"desktop\"}"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"user\"}"
      }
     ]
    },
    {
     "title": "Mobile",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"mobile\"}"
      }
     ]
    },
    {
     "title": "Guests",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"guest\"}"
      }
     ]
    },
    {
     "title": "Handheld",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "unpoller_device_stations{site_name=~\"$Site\", name=~\"$Gateway\",station_type=\"handheld\"}"
      }
     ]
    },
    {
     "title": "USG Load Average",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "unpoller_device_load_average_1{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} load1"
      },
      {
       "expr": "unpoller_device_load_average_15{site_name=~\"$Site\", name=~\"$Gateway\"}",
       "legendFormat": "{{name}} load15"
      }
     ]
    },
    {
     "title": "WAN Throughput",
     "type": "graph",
     "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Tx"
      }
     ]
    },
    {
     "title": "LAN Throughput",
     "type": "graph",
     "description": "Spikes on this graph that do not appear on the WAN graph indicate inter-VLAN-routing. Rx is on the negative axis.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Rx"
      },
      {
       "expr": "rate(unpoller_device_lan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Bytes Tx"
      }
     ]
    },
    {
     "title": "WAN Packets",
     "type": "graph",
     "description": "PPS on the WAN interface. Rx is on the negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_receive_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Tx"
      }
     ]
    },
    {
     "title": "LAN Packets",
     "type": "graph",
     "description": "PPS on the LAN interface. Rx is on the negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Rx"
      },
      {
       "expr": "rate(unpoller_device_lan_transmit_packets_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Packets Tx"
      }
     ]
    },
    {
     "title": "WAN Multicast & Broadcast",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_transmit_broadcast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Broadcast Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_broadcast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Broadcast Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_multicast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}}  Multicast Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_multicast_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Multicast Tx"
      }
     ]
    },
    {
     "title": "WAN Drops & Errors",
     "type": "graph",
     "description": "May show problems with your WAN interface. Rx on negative axis.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_wan_transmit_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Drops Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Drops Rx"
      },
      {
       "expr": "rate(unpoller_device_wan_transmit_errors_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Errors Tx"
      },
      {
       "expr": "rate(unpoller_device_wan_receive_errors_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Errors Rx"
      }
     ]
    },
    {
     "title": "LAN Drops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "pps", "label": "packets / second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_lan_receive_dropped_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
       "legendFormat": "{{name}} {{port}} Dropped Rx"
      }
     ]
    }
   ]
  },
  {
   "title": "Purposely Empty Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}