global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1


# We just include all of the possible scrape candidates here. 
# If the particular set up doesn't use them, they'll just fail. So sad. 
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus/metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: node
  file_sd_configs:
  - files:
    - 'targets.json'

- job_name: 'unifi-poller'
  scrape_interval: 30s
  static_configs:
  - targets: ['unifi-poller:9130']

- job_name: 'pihole'
  static_configs:
    - targets: ['pihole-exporter:9617']