
services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=homebots_traefik-net"

      - "--entrypoints.web.address=:80"
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.websecure.address=:443'

      # reenable this to try teh cloudflares.
      # - '--certificatesresolvers.le.acme.dnschallenge=true'
      # - '--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare'

    environment:
      # you may choose to use secrets instead of environment variables like this
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOSTNAME}`) && (PathPrefix(`/traefik`) || PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      - "traefik.http.routers.traefik.middlewares=traefik-strip"
        # specific middleware for traefik (it enables the dashboard at mydomain.com/traefik)
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"

    networks:
      - traefik-net

networks:
  traefik-net:
