  services:
    tailscale: 
      container_name: tailscale 
      hostname: tailscale-${HOSTNAME}
      image: tailscale/tailscale:stable 
      volumes: 
        - ./tailscale:/var/lib # State data will be stored in this directory 
        - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
      network_mode: host

      cap_add: # Required for tailscale to work 
        - net_admin 
        - sys_module 
      environment:
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_EXTRA_ARGS=--advertise-exit-node
        - TS_HOSTNAME=${HOSTNAME}
      restart: unless-stopped
